In [14]:
import numpy as np
import pandas as pd

#Making dataframes
movies = pd.read_csv('tmdb_5000_movies.csv')
movies.head(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
5,258000000,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""na...",http://www.sonypictures.com/movies/spider-man3/,559,"[{""id"": 851, ""name"": ""dual identity""}, {""id"": ...",en,Spider-Man 3,The seemingly invincible Spider-Man goes up ag...,115.699814,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-01,890871626,139.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,The battle within.,Spider-Man 3,5.9,3576
6,260000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://disney.go.com/disneypictures/tangled/,38757,"[{""id"": 1562, ""name"": ""hostage""}, {""id"": 2343,...",en,Tangled,When the kingdom's most wanted-and most charmi...,48.681969,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2010-11-24,591794936,100.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,They're taking adventure to new lengths.,Tangled,7.4,3330
7,280000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,"[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": ...",en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,134.279229,"[{""name"": ""Marvel Studios"", ""id"": 420}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2015-04-22,1405403694,141.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Age Has Come.,Avengers: Age of Ultron,7.3,6767
8,250000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://harrypotter.warnerbros.com/harrypottera...,767,"[{""id"": 616, ""name"": ""witch""}, {""id"": 2343, ""n...",en,Harry Potter and the Half-Blood Prince,"As Harry begins his sixth year at Hogwarts, he...",98.885637,"[{""name"": ""Warner Bros."", ""id"": 6194}, {""name""...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2009-07-07,933959197,153.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Dark Secrets Revealed,Harry Potter and the Half-Blood Prince,7.4,5293
9,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.batmanvsupermandawnofjustice.com/,209112,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 7002...",en,Batman v Superman: Dawn of Justice,Fearing the actions of a god-like Super Hero l...,155.790452,"[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""A...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2016-03-23,873260194,151.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Justice or revenge,Batman v Superman: Dawn of Justice,5.7,7004

In [16]:
movies = movies.rename(columns={"id":"movie_id"})

In [17]:
movies = movies[['movie_id','title','genres','vote_average']]
movies.head()

,movie_id,title,genres,vote_average
0,19995,Avatar,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",7.2
1,285,Pirates of the Caribbean: At World's End,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",6.9
2,206647,Spectre,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.3
3,49026,The Dark Knight Rises,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",7.6
4,49529,John Carter,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",6.1

In [6]:
movies.isnull().sum()

movie_id    0
title       0
genres      0
dtype: int64

In [35]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [18]:
import ast

def convert(text):            #helper function to fetch appropriate element from genres and keywords
    lst = []
    for i in ast.literal_eval(text):        #converts string of list to list
        lst.append(i['name'])
    return lst

movies['genres'] = movies['genres'].apply(convert)
movies.head()

,movie_id,title,genres,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",6.9
2,206647,Spectre,"[Action, Adventure, Crime]",6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]",6.1

In [37]:
# genres = set(g for G in movies['genres'] for g in G)

# for g in genres:
#     movies[g] = movies.genres.transform(lambda x: int(g in x))

In [38]:
movies.head()

,movie_id,title,genres
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]"
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]"
2,206647,Spectre,"[Action, Adventure, Crime]"
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]"
4,49529,John Carter,"[Action, Adventure, Science Fiction]"

In [19]:
def filter_movies_by_genres(df, genres):
    """
    Filter movies DataFrame based on genres entered by the user.
    
    Args:
        df (DataFrame): DataFrame containing movies and genres.
        genres (list): List of genres entered by the user.
        
    Returns:
        DataFrame: Filtered DataFrame containing movies matching the genres.
    """
    filtered_df = df[df['genres'].apply(lambda x: all(genre in x for genre in genres))]
    return filtered_df

In [20]:
user_genres = ['Drama','Romance','Comedy','Thriller','Action']
# user_genres = ['Drama','Action']
filtered_movies = filter_movies_by_genres(movies, user_genres)
len(filtered_movies)

0

In [58]:
flat_genres = [genre for movie_genres in movies['genres'] for genre in movie_genres]
flat_genres

['Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Adventure',
 'Crime',
 'Action',
 'Crime',
 'Drama',
 'Thriller',
 'Action',
 'Adventure',
 'Science Fiction',
 'Fantasy',
 'Action',
 'Adventure',
 'Animation',
 'Family',
 'Action',
 'Adventure',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Family',
 'Action',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Fantasy',
 'Action',
 'Science Fiction',
 'Adventure',
 'Action',
 'Thriller',
 'Crime',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Adventure',
 'Western',
 'Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'Adventure',
 'Family',
 'Fantasy',
 'Science Fiction',
 'Action',
 'Adventure',
 'Adventure',
 'Action',
 'Fantasy',
 'Action',
 'Comedy',
 'Science Fiction',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Drama',
 'Action',
 'Drama',
 'Romance',
 'Thriller',
 'Adventure',
 'Action',
 'Science Fiction',
 'Thriller',
 'Action',
 'Adventure',
 'Science Fiction',
 'Action',
 'Adventure',
 'Science Fiction',
 'Thriller',
 'Action',
 'Adventure',
 'Thriller',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Family',
 'Fantasy',
 'Adventure',
 'Adventure',
 'Action',
 'Science Fiction',
 'Thriller',
 'Animation',
 'Family',
 'Science Fiction',
 'Action',
 'Adventure',
 'Science Fiction',
 'Action',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Family',
 'Action',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Action',
 'Science Fiction',
 'Animation',
 'Family',
 'Adventure',
 'Comedy',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Animation',
 'Family',
 'Comedy',
 'Action',
 'Science Fiction',
 'Thriller',
 'Action',
 'Action',
 'Drama',
 'Horror',
 'Science Fiction',
 'Thriller',
 'Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'Action',
 'Adventure',
 'Science Fiction',
 'Action',
 'Family',
 'Fantasy',
 'Drama',
 'Romance',
 'Adventure',
 'Fantasy',
 'Action',
 'Romance',
 'Action',
 'Science Fiction',
 'Adventure',
 'Action',
 'Science Fiction',
 'Adventure',
 'Adventure',
 'Action',
 'Adventure',
 'Animation',
 'Family',
 'Animation',
 'Adventure',
 'Comedy',
 'Family',
 'Action',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Animation',
 'Family',
 'Action',
 'Comedy',
 'Crime',
 'Thriller',
 'Action',
 'Adventure',
 'Science Fiction',
 'Animation',
 'Drama',
 'Science Fiction',
 'Fantasy',
 'Action',
 'Adventure',
 'Action',
 'Adventure',
 'Adventure',
 'Family',
 'Fantasy',
 'Science Fiction',
 'Drama',
 'Action',
 'Crime',
 'Thriller',
 'Animation',
 'Comedy',
 'Family',
 'Adventure',
 'Animation',
 'Family',
 'Adventure',
 'Science Fiction',
 'Action',
 'Science Fiction',
 'Adventure',
 'Adventure',
 'Drama',
 'Family',
 'Action',
 'Adventure',
 'Comedy',
 'Science Fiction',
 'Western',
 'Adventure',
 'Action',
 'Fantasy',
 'Action',
 'Adventure',
 'Crime',
 'Fantasy',
 'Science Fiction',
 'Fantasy',
 'Comedy',
 'Family',
 'Action',
 'Science Fiction',
 'Adventure',
 'Action',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Drama',
 'Comedy',
 'Animation',
 'Family',
 'Family',
 'Adventure',
 'Drama',
 'Fantasy',
 'Adventure',
 'Action',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Drama',
 'Fantasy',
 'Adventure',
 'Action',
 'Family',
 'Romance',
 'Science Fiction',
 'Action',
 'Drama',
 'Thriller',
 'Action',
 'Adventure',
 'Science Fiction',
 'Romance',
 'Drama',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Comedy',
 'Adventure',
 'Fantasy',
 'Animation',
 'Family',
 'Adventure',
 'Family',
 'Mystery',
 'Science Fiction',
 'Adventure',
 'Family',
 'Animation',
 'Action',
 'Comedy',
 'Family',
 'Animation',
 'Comedy',
 'Adventure',
 'Adventure',
 'Animation',
 'Family',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Fantasy',
 'Adventure',
 'Animation',
 'Family',
 'Action',
 'Thriller',
 'Science Fiction',
 'Action',
 'Science Fiction',
 'Adventure',
 'Adventure',
 'Drama',
 'Science Fiction',
 'Action',
 'Thriller',
 'Science Fiction',
 'Mystery',
 'Adventure',
 'Action',
 'Adventure',
 'Drama',
 'Horror',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Crime',
 'Thriller',
 'Fantasy',
 'Drama',
 'Thriller',
 'Mystery',
 'Romance',
 'Action',
 'Science Fiction',
 'Adventure',
 'Action',
 'Adventure',
 'Science Fiction',
 'Fantasy',
 'Adventure',
 'Action',
 'Comedy',
 'Drama',
 'Adventure',
 'Action',
 'Drama',
 'Thriller',
 'Fantasy',
 'Fantasy',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Action',
 'Adventure',
 'Fantasy',
 'Science Fiction',
 'Action',
 'Thriller',
 'Adventure',
 'Adventure',
 'Family',
 'Fantasy',
 'History',
 'Romance',
 'War',
 'Adventure',
 'Science Fiction',
 'Action',
 'War',
 'History',
 'Action',
 'Adventure',
 'Drama',
 'Romance',
 'Adventure',
 'Fantasy',
 'Family',
 'Mystery',
 'Adventure',
 'Fantasy',
 'Family',
 'Fantasy',
 'Action',
 'Drama',
 'Horror',
 'Action',
 'Thriller',
 'Science Fiction',
 'Adventure',
 'Comedy',
 'Family',
 'Fantasy',
 'Animation',
 'Comedy',
 'Family',
 'Fantasy',
 'Action',
 'Crime',
 'Drama',
 'Family',
 'Animation',
 'Adventure',
 'Fantasy',
 'Action',
 'Comedy',
 'Family',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Animation',
 'Adventure',
 'Family',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Thriller',
 'Thriller',
 'Mystery',
 'Adventure',
 'Fantasy',
 'Action',
 'Animation',
 'Family',
 'Adventure',
 'Comedy',
 'Fantasy',
 'Action',
 'Adventure',
 'Family',
 'Comedy',
 'Adventure',
 'Comedy',
 'Fantasy',
 'Action',
 'Adventure',
 'Thriller',
 'Drama',
 'Horror',
 'Thriller',
 'Family',
 'Animation',
 'Adventure',
 'Comedy',
 'Animation',
 'Family',
 'Action',
 'Adventure',
 'Family',
 'Fantasy',
 'Adventure',
 'Action',
 'Thriller',
 'Action',
 'Drama',
 'Thriller',
 'Adventure',
 'Animation',
 'Family',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Adventure',
 'Family',
 'Fantasy',
 'Animation',
 'Adventure',
 'Family',
 'Adventure',
 'Drama',
 'War',
 'Animation',
 'Family',
 'Adventure',
 'Action',
 'Thriller',
 'Action',
 'Fantasy',
 'Comedy',
 'Action',
 'Thriller',
 'Science Fiction',
 'Adventure',
 'Action',
 'Adventure',
 'Comedy',
 'Science Fiction',
 'Adventure',
 'Action',
 'Animation',
 'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Action',
 'Thriller',
 'Adventure',
 'Fantasy',
 'Animation',
 'Family',
 'Comedy',
 'Drama',
 'Action',
 'War',
 'History',
 'Adventure',
 'Drama',
 'Action',
 'Science Fiction',
 'Action',
 'Adventure',
 'Fantasy',
 'Action',
 'Fantasy',
 'Action',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Fantasy',
 'Action',
 'Action',
 'Mystery',
 'Science Fiction',
 'Action',
 'Adventure',
 'Comedy',
 'Crime',
 'Thriller',
 'Drama',
 'Action',
 'Science Fiction',
 'Adventure',
 'Action',
 'Science Fiction',
 'Thriller',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Mystery',
 'Adventure',
 'Action',
 'Animation',
 'Fantasy',
 'Science Fiction',
 'Thriller',
 'Action',
 'Adventure',
 'Science Fiction',
 'Adventure',
 'Action',
 'Thriller',
 'Adventure',
 'Adventure',
 'Fantasy',
 'Drama',
 'Romance',
 'Animation',
 'Comedy',
 'Family',
 'Science Fiction',
 'Action',
 'Adventure',
 'Adventure',
 'Family',
 'Fantasy',
 'Western',
 'Drama',
 'Adventure',
 'Thriller',
 'Animation',
 'Family',
 'Animation',
 'Comedy',
 'Family',
 'Western',
 'Adventure',
 'Family',
 'Animation',
 'Adventure',
 'Comedy',
 'Action',
 'Drama',
 'Mystery',
 'Thriller',
 'Adventure',
 'Animation',
 'Family',
 'Comedy',
 'Science Fiction',
 'Action',
 'Adventure',
 'Adventure',
 'Action',
 'Science Fiction',
 'Fantasy',
 'Comedy',
 'Animation',
 'Science Fiction',
 'Family',
 'Adventure',
 'Thriller',
 'Science Fiction',
 'Adventure',
 'Action',
 'Comedy',
 'Thriller',
 'Crime',
 'Action',
 'Adventure',
 'Animation',
 'Family',
 'Fantasy',
 'Action',
 'Mystery',
 'Thriller',
 'Drama',
 'Adventure',
 'Adventure',
 'Animation',
 'Mystery',
 'Adventure',
 'Fantasy',
 'Family',
 'Drama',
 'Science Fiction',
 'Action',
 'Adventure',
 'Animation',
 'Family',
 'Adventure',
 'Comedy',
 'Fantasy',
 'Family',
 'Animation',
 'Action',
 'Comedy',
 'Family',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Family',
 'Fantasy',
 'Action',
 'Comedy',
 'Crime',
 'Adventure',
 'Fantasy',
 'Action',
 'Science Fiction',
 'Adventure',
 'Thriller',
 'Thriller',
 'Mystery',
 'Animation',
 'Adventure',
 'Comedy',
 'Family',
 'Adventure',
 'Action',
 'Science Fiction',
 'Thriller',
 'Action',
 'Thriller',
 'Crime',
 'Adventure',
 'Action',
 'Crime',
 'Mystery',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Adventure',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Thriller',
 'Action',
 'Crime',
 'Fantasy',
 'Family',
 'Comedy',
 'Fantasy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Thriller',
 'Adventure',
 'Action',
 'Thriller',
 'Drama',
 'Adventure',
 'Fantasy',
 'Action',
 'Thriller',
 'Adventure',
 'Drama',
 'Action',
 'Thriller',
 'Action',
 'Fantasy',
 'Horror',
 'Action',
 'Thriller',
 'Action',
 'Adventure',
 'Comedy',
 'Science Fiction',
 'Adventure',
 'Mystery',
 'Family',
 'Adventure',
 'Animation',
 'Comedy',
 'Science Fiction',
 'Action',
 'Drama',
 'Thriller',
 'Action',
 'Science Fiction',
 'Action',
 'Science Fiction',
 'Action',
 'Family',
 'Science Fiction',
 'Comedy',
 'Drama',
 'Romance',
 'Action',
 'Comedy',
 'Action',
 'Science Fiction',
 'Adventure',
 'Mystery',
 'Science Fiction',
 'Adventure',
 'Action',
 'Adventure',
 'Action',
 'Science Fiction',
 'Animation',
 'Comedy',
 'Family',
 'Action',
 'Science Fiction',
 'Adventure',
 'Fantasy',
 'Adventure',
 'Action',
 'Science Fiction',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Fantasy',
 'Fantasy',
 'Adventure',
 'Comedy',
 'Family',
 'Drama',
 'Action',
 'History',
 'War',
 'Action',
 'Adventure',
 'Drama',
 'Science Fiction',
 'Action',
 'Adventure',
 'Fantasy',
 'Comedy',
 'Science Fiction',
 'Thriller',
 'Drama',
 'Action',
 'Adventure',
 'Thriller',
 'Fantasy',
 'Action',
 'Adventure',
 'Comedy',
 'Action',
 'Adventure',
 'Science Fiction',
 'Action',
 'Adventure',
 'Comedy',
 'Family',
 'Fantasy',
 'Action',
 'Drama',
 'Thriller',
 'Adventure',
 'Action',
 'Thriller',
 'Drama',
 'History',
 'War',
 'Action',
 'Thriller',
 'Crime',
 'Action',
 'Comedy',
 'Drama',
 'Thriller',
 'Adventure',
 'Science Fiction',
 'Thriller',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Comedy',
 'Action',
 'War',
 'Animation',
 'Family',
 'Adventure',
 'Comedy',
 'Fantasy',
 'Animation',
 'Family',
 'Adventure',
 'Science Fiction',
 'Action',
 'Science Fiction',
 'Drama',
 'Fantasy',
 'Family',
 'Comedy',
 'Animation',
 'Action',
 'Adventure',
 'Thriller',
 'Science Fiction',
 'Action',
 'Adventure',
 'Action',
 'Thriller',
 'Adventure',
 'Fantasy',
 'Action',
 'Action',
 'Adventure',
 'Comedy',
 'Drama',
 'Comedy',
 'Fantasy',
 'Family',
 'Action',
 'Science Fiction',
 'Drama',
 'Action',
 'Adventure',
 'History',
 'War',
 'Animation',
 'Fantasy',
 'Family',
 'Comedy',
 'Romance',
 'Family',
 'Animation',
 'Music',
 'Drama',
 'Adventure',
 'Science Fiction',
 'Action',
 'Thriller',
 'Science Fiction',
 'Adventure',
 'Comedy',
 'Romance',
 'Action',
 'Crime',
 'Thriller',
 'Action',
 'Drama',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Mystery',
 'Adventure',
 'Fantasy',
 'Family',
 'Adventure',
 'Action',
 'Thriller',
 'Thriller',
 'Science Fiction',
 'Action',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'History',
 'Crime',
 'Drama',
 'Drama',
 'Crime',
 'Action',
 'Thriller',
 'Thriller',
 'Drama',
 'Crime',
 'Comedy',
 'Romance',
 'Action',
 'Comedy',
 'Crime',
 'Action',
 'Drama',
 'Mystery',
 'Thriller',
 'Drama',
 'Western',
 'Drama',
 'Animation',
 'Family',
 'Adventure',
 'Animation',
 'Comedy',
 'Family',
 'Fantasy',
 'Action',
 'Adventure',
 'Thriller',
 'Adventure',
 'Action',
 'Thriller',
 'Mystery',
 'Fantasy',
 'Action',
 'Adventure',
 'Family',
 'Family',
 'Fantasy',
 'Animation',
 'Adventure',
 'Family',
 'Fantasy',
 'Action',
 'Thriller',
 'Romance',
 'Action',
 'Fantasy',
 'Horror',
 'Mystery',
 'Drama',
 'Thriller',
 'Action',
 'Crime',
 'Drama',
 'Comedy',
 'Action',
 'Crime',
 'Fantasy',
 'Adventure',
 'Action',
 'Thriller',
 'Science Fiction',
 'Drama',
 'Science Fiction',
 'Animation',
 'Adventure',
 'Family',
 'Fantasy',
 'Action',
 'Crime',
 'Action',
 'Adventure',
 'Adventure',
 'Animation',
 'Family',
 'Fantasy',
 'Science Fiction',
 'Adventure',
 'Comedy',
 ...]

In [61]:
from collections import Counter
genre_counts = Counter(flat_genres)
genre_counts

Counter({'Drama': 2297,
         'Comedy': 1722,
         'Thriller': 1274,
         'Action': 1154,
         'Romance': 894,
         'Adventure': 790,
         'Crime': 696,
         'Science Fiction': 535,
         'Horror': 519,
         'Family': 513,
         'Fantasy': 424,
         'Mystery': 348,
         'Animation': 234,
         'History': 197,
         'Music': 185,
         'War': 144,
         'Documentary': 110,
         'Western': 82,
         'Foreign': 34,
         'TV Movie': 8})

In [24]:
movies.head()

,movie_id,title,genres,vote_average
0,19995,Avatar,"[Action, Adventure, Fantasy, Science Fiction]",7.2
1,285,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]",6.9
2,206647,Spectre,"[Action, Adventure, Crime]",6.3
3,49026,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]",7.6
4,49529,John Carter,"[Action, Adventure, Science Fiction]",6.1

In [40]:
def genre_filterer_by_fans(genres):
    filtered_movies = filter_movies_by_genres(movies, genres)
    sorted_frame = filtered_movies.sort_values(by='vote_average',ascending=False)
    # final = sorted_frame.iloc[0:20,0:1]
    return sorted_frame

In [38]:
def genre_filterer(genres):
    filtered_movies = filter_movies_by_genres(movies, genres)
    # final = filtered_movies.iloc[0:20,0:1]
    # return final
    return filtered_movies

In [42]:
genres = ['Action','Drama']
genre_filterer_by_fans(genres)

,movie_id,title,genres,vote_average
2386,69848,One Man's Hero,"[Western, Action, Drama, History]",9.3
4535,346,Seven Samurai,"[Action, Drama]",8.2
65,155,The Dark Knight,"[Drama, Action, Crime, Thriller]",8.2
3940,670,Oldboy,"[Drama, Thriller, Mystery, Action]",8.0
1850,111,Scarface,"[Action, Crime, Drama, Thriller]",8.0
...,...,...,...,...
4402,56491,In Her Line of Fire,"[Drama, Action, Thriller]",3.3
3689,10914,All Hat,"[Action, Comedy, Drama, Western]",1.0
4638,378237,Amidst the Devil's Wings,"[Drama, Action, Crime]",0.0
4708,354624,Heroes of Dirt,"[Action, Drama]",0.0
4275,295914,Queen of the Mountains,"[Drama, Action]",0.0